# This is a basic workflow that is manually triggered

name: Auto Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  push:
    branches:
    - main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo /usr/local/bin/start-bot.sh
            exit
