name: Deploy to Server (non-stable)

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  check-if-success:
    if: >
      github.event.workflow_run.conclusion == 'success' && 
      (!contains(github.event.workflow_run.head_branch, 'alpha') || 
       !contains(github.event.workflow_run.head_branch, 'beta') || 
       !contains(github.event.workflow_run.head_branch, 'rc'))
    runs-on: ubuntu-latest
    steps:
      - name: Start the Bot
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo /usr/local/bin/start-kujow.sh
            exit
